//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria.SampleApps.Common.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class SampleAppsSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SampleAppsSettings defaultInstance = ((SampleAppsSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SampleAppsSettings())));
        
        public static SampleAppsSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YqB3ed4thSGNMkW8qmD3Xg6d7vyvV5b9")]
        public string auth_key {
            get {
                return ((string)(this["auth_key"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75000")]
        public long client_no {
            get {
                return ((long)(this["client_no"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("setEnglish")]
        public string set_name {
            get {
                return ((string)(this["set_name"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://secure.future.stage.ariasystems.net/api/direct_post.php")]
        public string PaymentHandleUrl {
            get {
                return ((string)(this["PaymentHandleUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reg")]
        public string DirectPostRegMode {
            get {
                return ((string)(this["DirectPostRegMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~/logs/")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
        }
    }
}
