//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aria.SDK.AriaServices.AriaWebServices {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class AriaSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AriaSettings defaultInstance = ((AriaSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AriaSettings())));
        
        public static AriaSettings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
